<?php

class Seeder extends Model {

    protected $tableName = "artists";
    public $count;
    public $limit = 21;

    function add(Artists $artists){
        for ($i=1; $i < 100; $i++) { 

            $first_name = $this->womenNames[$i];
            $last_name = $this->womenLastNames[$i];
            $link = Utils::generateLink($first_name . " " . $last_name);
            $artist = $artists->getArtist($link);
            $index = 2;
            while($artist){
                $link = Utils::generateLink($first_name . " " . $last_name. "-" . $index);
                $artist = $artists->getArtist($link);
                $index++;
            }
            $profession = $this->womenProfessions[array_rand($this->womenProfessions)];
            $content = $this->contents[array_rand($this->contents)];
            $photo = "upload/artists/women/" . rand(1 , 99) . ".jpg";
            $this->table()->insert("ssssss", 
                [
                    "link" => $link,
                    "first_name" => $first_name, 
                    "last_name" => $last_name, 
                    "profession" => $profession, 
                    "content" => $content, 
                    "photo" => $photo
                ]
            );
        }
    }

    private $womenNames = [
        "Jana",
        "Marie",
        "Eva",
        "Hana",
        "Anna",
        "Lenka",
        "Kateřina",
        "Lucie",
        "Věra",
        "Alena",
        "Petra",
        "Veronika",
        "Jaroslava",
        "Tereza",
        "Martina",
        "Michaela",
        "Jitka",
        "Helena",
        "Ludmila",
        "Zdeňka",
        "Ivana",
        "Monika",
        "Eliška",
        "Zuzana",
        "Markéta",
        "Jarmila",
        "Barbora",
        "Jiřina",
        "Marcela",
        "Kristýna",
        "Dana",
        "Dagmar",
        "Adéla",
        "Pavla",
        "Vlasta",
        "Miroslava",
        "Andrea",
        "Irena",
        "Božena",
        "Klára",
        "Libuše",
        "Marta",
        "Šárka",
        "Nikola",
        "Karolína",
        "Iveta",
        "Pavlína",
        "Natálie",
        "Olga",
        "Blanka",
        "Gabriela",
        "Renata",
        "Aneta",
        "Simona",
        "Růžena",
        "Radka",
        "Daniela",
        "Denisa",
        "Iva",
        "Zdenka",
        "Milada",
        "Milena",
        "Romana",
        "Miloslava",
        "Miluše",
        "Ilona",
        "Anežka",
        "Soňa",
        "Kamila",
        "Stanislava",
        "Nela",
        "Vladimíra",
        "Naděžda",
        "Květoslava",
        "Renáta",
        "Danuše",
        "Vendula",
        "Drahomíra",
        "Julie",
        "Jindřiška",
        "Emilie",
        "Viktorie",
        "Alžběta",
        "Sára",
        "Štěpánka",
        "Dominika",
        "Ema",
        "Sabina",
        "Magdalena",
        "Nikol",
        "Sofie",
        "Mária",
        "Františka",
        "Ladislava",
        "Bohumila",
        "Alice",
        "Magdaléna",
        "Žaneta",
        "Linda",
        "Alexandra" 
    ];
    
    private $womenLastNames = [
        "Nováková",
        "Svobodová",
        "Novotná",
        "Dvořáková",
        "Černá",
        "Procházková",
        "Kučerová",
        "Veselá",
        "Horáková",
        "Němcová",
        "Marková",
        "Pokorná",
        "Pospíšilová",
        "Hájková",
        "Králová",
        "Jelínková",
        "Růžičková",
        "Benešová",
        "Fialová",
        "Sedláčková",
        "Doležalová",
        "Zemanová",
        "Kolářová",
        "Navrátilová",
        "Čermáková",
        "Vaňková",
        "Urbanová",
        "Kratochvílová",
        "Šimková",
        "Blažková",
        "Křížová",
        "Kopecká",
        "Kovářová",
        "Bartošová",
        "Vlčková",
        "Poláková",
        "Konečná",
        "Musilová",
        "Čechová",
        "Malá",
        "Staňková",
        "Štěpánková",
        "Holubová",
        "Šťastná",
        "Kadlecová",
        "Dostálová",
        "Soukupová",
        "Marešová",
        "Sýkorová",
        "Valentová",
        "Moravcová",
        "Vávrová",
        "Tichá",
        "Matoušková",
        "Bláhová",
        "Říhová",
        "Machová",
        "Mašková",
        "Ševčíková",
        "Burešová",
        "Šmídová",
        "Dušková",
        "Krejčová",
        "Pavlíková",
        "Jandová",
        "Hrušková",
        "Havlíčková",
        "Hrubá",
        "Beranová",
        "Lišková",
        "Tomanová",
        "Vacková",
        "Bednářová",
        "Žáková",
        "Vítková",
        "Macháčková",
        "Bártová",
        "Tůmová",
        "Jarošová",
        "Janečková",
        "Sedláková",
        "Kašparová",
        "Müllerová",
        "Stejskalová",
        "Pešková",
        "Fišerová",
        "Švecová",
        "Matějková",
        "Bílková",
        "Slavíková",
        "Ježková",
        "Němečková",
        "Strnadová",
        "Krausová",
        "Beránková",
        "Horáčková",
        "Brožová",
        "Kubíčková",
        "Horváthová",
        "Petrová"
    ];

    private $womenProfessions = ["Herečka", "Zpěvačka", "Moderátorka"]; 

    private $contents = [
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloribus, voluptatem?",
        "A iste similique expedita harum, necessitatibus libero numquam delectus ratione.",
        "Iste debitis dolore, voluptate inventore corrupti rerum alias magnam dignissimos.",
        "Quam porro reiciendis nemo harum nam omnis culpa ipsa consequuntur!",
        "Dolores debitis quia beatae ducimus dolor fuga autem, velit eos.",
        "Exercitationem qui tempora facilis voluptate ex cumque architecto voluptatem eaque?",
        "Provident repellendus sit saepe harum facere, modi doloremque excepturi consequatur!",
        "Neque fuga iure voluptatum tempore commodi minima esse, quia nisi?",
        "Sequi reprehenderit dolorum pariatur provident animi! Esse ex tempora consequuntur.",
        "Nesciunt cum est asperiores voluptatum qui consequuntur explicabo, quasi maxime.",
        "Voluptas reiciendis itaque dolores possimus fugit magnam amet a est!",
        "Iste soluta reprehenderit cupiditate libero quo minus reiciendis esse dicta.",
        "Vitae minus porro voluptas illo incidunt maiores, cupiditate in officia.",
        "Esse accusantium laborum dicta consequuntur rem. Corrupti accusamus laboriosam sed?",
        "Odit iste beatae aut at debitis nam eos ipsum nemo.",
        "Inventore alias architecto laborum? Porro, ullam doloribus. Officia, recusandae nihil.",
        "Eaque fuga animi repellendus tenetur pariatur aut veniam quis enim?",
        "Sed quos natus quia autem facilis repellendus accusamus quidem ad?",
        "Maiores alias eveniet mollitia. Vel nam nobis corporis deserunt? Dolor?",
        "Repellendus quis, culpa iusto ut dolor rem quisquam quos similique!"
    ];

}


